"""add presbyteries and churches tables

Revision ID: 251d6bd8f05e
Revises: 43fb1b81029f
Create Date: 2026-03-27 16:52:19.682381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '251d6bd8f05e'
down_revision: Union[str, None] = '43fb1b81029f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('presbyteries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('churches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('presbytery_id', sa.Integer(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['presbytery_id'], ['presbyteries.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_churches_presbytery_id', 'churches', ['presbytery_id'], unique=False)
    op.drop_index('ix_credentials_status', table_name='credentials')
    op.drop_index('uq_credential_cpf', table_name='credentials')
    op.drop_index('uq_credential_qr_code', table_name='credentials')
    op.drop_index('uq_credentials_email', table_name='credentials', postgresql_where='(email IS NOT NULL)')
    op.create_index(op.f('ix_credentials_email'), 'credentials', ['email'], unique=True)
    op.create_unique_constraint(None, 'credentials', ['cpf'])
    op.create_unique_constraint(None, 'credentials', ['qr_code'])
    op.alter_column('registration_payments', 'phone',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.alter_column('registration_payments', 'participation_type',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=20),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('registration_payments', 'participation_type',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('registration_payments', 'phone',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=30),
               existing_nullable=True)
    op.drop_constraint(None, 'credentials', type_='unique')
    op.drop_constraint(None, 'credentials', type_='unique')
    op.drop_index(op.f('ix_credentials_email'), table_name='credentials')
    op.create_index('uq_credentials_email', 'credentials', ['email'], unique=True, postgresql_where='(email IS NOT NULL)')
    op.create_index('uq_credential_qr_code', 'credentials', ['qr_code'], unique=True)
    op.create_index('uq_credential_cpf', 'credentials', ['cpf'], unique=True)
    op.create_index('ix_credentials_status', 'credentials', ['status'], unique=False)
    op.drop_index('ix_churches_presbytery_id', table_name='churches')
    op.drop_table('churches')
    op.drop_table('presbyteries')
    # ### end Alembic commands ###
