"""add team_sports many to many

Revision ID: 34755f63fe21
Revises: add_basketball_event_types
Create Date: 2026-03-20 16:52:54.409067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34755f63fe21'
down_revision: Union[str, None] = 'add_basketball_event_types'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team_sports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('sport_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sport_id'], ['sports.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_team_sports_sport_id'), 'team_sports', ['sport_id'], unique=False)
    op.create_index(op.f('ix_team_sports_team_id'), 'team_sports', ['team_id'], unique=False)
    op.create_index('uq_team_sport', 'team_sports', ['team_id', 'sport_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_team_sport', table_name='team_sports')
    op.drop_index(op.f('ix_team_sports_team_id'), table_name='team_sports')
    op.drop_index(op.f('ix_team_sports_sport_id'), table_name='team_sports')
    op.drop_table('team_sports')
    # ### end Alembic commands ###
