"""add_modalities_to_registration_payments

Revision ID: 43fb1b81029f
Revises: r1s2t3u4v5w6
Create Date: 2026-03-27 11:09:24.542262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43fb1b81029f'
down_revision: Union[str, None] = 'r1s2t3u4v5w6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


"""add_modalities_to_registration_payments

Revision ID: 43fb1b81029f
Revises: r1s2t3u4v5w6
Create Date: 2026-03-27 11:09:24.542262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43fb1b81029f'
down_revision: Union[str, None] = 'r1s2t3u4v5w6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('registration_payments', sa.Column('modalities', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('registration_payments', 'modalities')
    # ### end Alembic commands ###
