"""add image_url and refund fields to cantina

Revision ID: 459989ffd392
Revises: g1h2i3j4k5l6
Create Date: 2026-03-23 23:43:03.419654

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '459989ffd392'
down_revision: Union[str, None] = 'g1h2i3j4k5l6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cantin_orders', sa.Column('refunded_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('cantin_orders', sa.Column('refunded_by', sa.Integer(), nullable=True))
    op.add_column('cantin_orders', sa.Column('refund_reason', sa.String(length=300), nullable=True))
    op.create_foreign_key(None, 'cantin_orders', 'users', ['refunded_by'], ['id'], ondelete='SET NULL')
    op.add_column('cantin_products', sa.Column('image_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cantin_products', 'image_url')
    op.drop_constraint(None, 'cantin_orders', type_='foreignkey')
    op.drop_column('cantin_orders', 'refund_reason')
    op.drop_column('cantin_orders', 'refunded_by')
    op.drop_column('cantin_orders', 'refunded_at')
    # ### end Alembic commands ###
