"""add athlete_id to credentials

Revision ID: 7d23232c73fc
Revises: a1b2c3d4e5f6
Create Date: 2026-05-07 16:19:26.621659

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7d23232c73fc'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('credentials', sa.Column('athlete_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'credentials', 'athletes', ['athlete_id'], ['id'], ondelete='SET NULL')
    op.alter_column('game_results', 'extra_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Dados extras do resultado: sets de vôlei, W.O., pontos de tabela',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('game_results', 'extra_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Dados extras do resultado: sets de vôlei, W.O., pontos de tabela',
               existing_nullable=True)
    op.drop_constraint(None, 'credentials', type_='foreignkey')
    op.drop_column('credentials', 'athlete_id')
    # ### end Alembic commands ###
