"""add audit fields to game events and results

Revision ID: 86b27f89da45
Revises: c1a2b3c4d5e6
Create Date: 2026-03-19 15:58:29.155361

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '86b27f89da45'
down_revision: Union[str, None] = 'c1a2b3c4d5e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('championships', 'knockout_bracket',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='Cruzamentos do mata-mata definidos manualmente',
               existing_nullable=True)
    op.add_column('game_events', sa.Column('created_by', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_game_events_created_by'), 'game_events', ['created_by'], unique=False)
    op.create_foreign_key(None, 'game_events', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.add_column('game_results', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('game_results', sa.Column('updated_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'game_results', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'game_results', 'users', ['updated_by'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'game_results', type_='foreignkey')
    op.drop_constraint(None, 'game_results', type_='foreignkey')
    op.drop_column('game_results', 'updated_by')
    op.drop_column('game_results', 'created_by')
    op.drop_constraint(None, 'game_events', type_='foreignkey')
    op.drop_index(op.f('ix_game_events_created_by'), table_name='game_events')
    op.drop_column('game_events', 'created_by')
    op.alter_column('championships', 'knockout_bracket',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='Cruzamentos do mata-mata definidos manualmente',
               existing_nullable=True)
    # ### end Alembic commands ###
