"""add cost fields to cantin_products

Revision ID: 9df29e4ee3e6
Revises: b31aa7543863
Create Date: 2026-03-31 10:02:37.966927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9df29e4ee3e6'
down_revision: Union[str, None] = 'b31aa7543863'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cantin_products', sa.Column('cost_price', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('cantin_products', sa.Column('profit_margin', sa.Numeric(precision=5, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cantin_products', 'profit_margin')
    op.drop_column('cantin_products', 'cost_price')
    # ### end Alembic commands ###
