"""add championship phases and athlete free

Revision ID: a5696bb23f1f
Revises: fa8bb67fbad0
Create Date: 2026-03-18 12:09:54.040102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5696bb23f1f'
down_revision: Union[str, None] = 'fa8bb67fbad0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('athletes', 'team_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('athletes_team_id_fkey', 'athletes', type_='foreignkey')
    op.create_foreign_key(None, 'athletes', 'teams', ['team_id'], ['id'], ondelete='SET NULL')
    op.add_column('championships', sa.Column('current_phase', sa.String(length=50), nullable=True))
    op.add_column('championships', sa.Column('group_count', sa.Integer(), nullable=True))
    op.add_column('championships', sa.Column('group_phase_format', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('championships', 'group_phase_format')
    op.drop_column('championships', 'group_count')
    op.drop_column('championships', 'current_phase')
    op.drop_constraint(None, 'athletes', type_='foreignkey')
    op.create_foreign_key('athletes_team_id_fkey', 'athletes', 'teams', ['team_id'], ['id'], ondelete='CASCADE')
    op.alter_column('athletes', 'team_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
