"""add cantin_reservations and pdv_name

Revision ID: b15d1b16b82b
Revises: ffddcd195d6b
Create Date: 2026-05-28 14:10:41.632454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b15d1b16b82b'
down_revision: Union[str, None] = 'ffddcd195d6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cantin_reservations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pdv_id', sa.Integer(), nullable=False),
    sa.Column('customer_name', sa.String(length=150), nullable=False),
    sa.Column('items', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('attended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attended_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['attended_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('cantin_pdv_config', sa.Column('pdv_name', sa.String(length=100), nullable=True))
    op.drop_column('feedbacks', 'page')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feedbacks', sa.Column('page', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('cantin_pdv_config', 'pdv_name')
    op.drop_table('cantin_reservations')
    # ### end Alembic commands ###
