"""fix varchar lengths in registration_payments

Revision ID: b31aa7543863
Revises: d9e932ce3744
Create Date: 2026-03-28 08:56:42.655678

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b31aa7543863'
down_revision: Union[str, None] = 'd9e932ce3744'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
