"""add expires_at to cantin_reservations

Revision ID: c411b8c29812
Revises: b15d1b16b82b
Create Date: 2026-05-28 14:48:17.785943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c411b8c29812'
down_revision: Union[str, None] = 'b15d1b16b82b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cantin_reservations', sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cantin_reservations', 'expires_at')
    # ### end Alembic commands ###
