"""add_modality_mappings_table

Revision ID: d9e932ce3744
Revises: 251d6bd8f05e
Create Date: 2026-03-27 18:38:11.884543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9e932ce3744'
down_revision: Union[str, None] = '251d6bd8f05e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('modality_mappings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('keyword', sa.String(length=200), nullable=False),
    sa.Column('sport_slug', sa.String(length=50), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_modality_mappings_keyword', 'modality_mappings', ['keyword'], unique=False)
    op.create_index('ix_modality_mappings_slug', 'modality_mappings', ['sport_slug'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_modality_mappings_slug', table_name='modality_mappings')
    op.drop_index('ix_modality_mappings_keyword', table_name='modality_mappings')
    op.drop_table('modality_mappings')
    # ### end Alembic commands ###
