"""initial tables

Revision ID: fa8bb67fbad0
Revises: 
Create Date: 2026-03-17 15:23:46.509324

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fa8bb67fbad0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.Enum('futsal', 'volleyball', 'basketball', 'running', 'boardgame', name='sport_slug'), nullable=False),
    sa.Column('rules_config', postgresql.JSON(astext_type=sa.Text()), nullable=False, comment='Configuração de regras específicas da modalidade (ex: pontuação, sets, tempos)'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('role', sa.Enum('admin', 'organizer', name='user_role'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('championships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('sport_id', sa.Integer(), nullable=False),
    sa.Column('format', sa.Enum('round_robin', 'elimination', 'hybrid', name='championship_format'), nullable=False),
    sa.Column('status', sa.Enum('draft', 'active', 'finished', name='championship_status'), nullable=False),
    sa.Column('rules_config', postgresql.JSON(astext_type=sa.Text()), nullable=False, comment='Critérios de classificação: pontos por vitória/empate, saldo de gols, etc.'),
    sa.Column('extra_data', postgresql.JSON(astext_type=sa.Text()), nullable=True, comment='Dados adicionais livres por modalidade (ex: número de sets, tempo de jogo)'),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sport_id'], ['sports.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_championships_created_by'), 'championships', ['created_by'], unique=False)
    op.create_index('ix_championships_sport_id', 'championships', ['sport_id'], unique=False)
    op.create_index('ix_championships_status', 'championships', ['status'], unique=False)
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('sport_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sport_id'], ['sports.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_teams_created_by', 'teams', ['created_by'], unique=False)
    op.create_index(op.f('ix_teams_sport_id'), 'teams', ['sport_id'], unique=False)
    op.create_table('athletes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('number', sa.Integer(), nullable=True, comment='Número da camisa'),
    sa.Column('position', sa.String(length=50), nullable=True, comment='Posição ou função na equipe'),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('photo_url', sa.String(length=500), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_athletes_team_id'), 'athletes', ['team_id'], unique=False)
    op.create_table('championship_teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('championship_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['championship_id'], ['championships.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_championship_teams_championship_id'), 'championship_teams', ['championship_id'], unique=False)
    op.create_index(op.f('ix_championship_teams_team_id'), 'championship_teams', ['team_id'], unique=False)
    op.create_index('uq_championship_team', 'championship_teams', ['championship_id', 'team_id'], unique=True)
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('championship_id', sa.Integer(), nullable=False),
    sa.Column('home_team_id', sa.Integer(), nullable=False),
    sa.Column('away_team_id', sa.Integer(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('venue', sa.String(length=200), nullable=True),
    sa.Column('status', sa.Enum('scheduled', 'live', 'finished', name='game_status'), nullable=False),
    sa.Column('phase', sa.String(length=50), nullable=True, comment='Ex: grupos, quartas, semifinal, final'),
    sa.Column('round_number', sa.Integer(), nullable=True, comment='Número da rodada dentro da fase'),
    sa.Column('extra_data', postgresql.JSON(astext_type=sa.Text()), nullable=True, comment='Dados extras por modalidade (ex: sets de vôlei, parciais de basquete)'),
    sa.ForeignKeyConstraint(['away_team_id'], ['teams.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['championship_id'], ['championships.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['home_team_id'], ['teams.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_games_away_team_id', 'games', ['away_team_id'], unique=False)
    op.create_index('ix_games_championship_id', 'games', ['championship_id'], unique=False)
    op.create_index('ix_games_home_team_id', 'games', ['home_team_id'], unique=False)
    op.create_index('ix_games_scheduled_at', 'games', ['scheduled_at'], unique=False)
    op.create_index('ix_games_status', 'games', ['status'], unique=False)
    op.create_table('game_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('athlete_id', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.Enum('goal', 'yellow_card', 'red_card', 'point', 'foul', name='game_event_type'), nullable=False),
    sa.Column('minute', sa.Integer(), nullable=True, comment='Minuto ou momento do evento'),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.ForeignKeyConstraint(['athlete_id'], ['athletes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_game_events_athlete_id', 'game_events', ['athlete_id'], unique=False)
    op.create_index('ix_game_events_game_id', 'game_events', ['game_id'], unique=False)
    op.create_index('ix_game_events_team_id', 'game_events', ['team_id'], unique=False)
    op.create_index('ix_game_events_type', 'game_events', ['event_type'], unique=False)
    op.create_table('game_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('home_score', sa.Integer(), nullable=False),
    sa.Column('away_score', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True, comment='Observações: W.O., prorrogação, etc.'),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_game_results_game_id'), 'game_results', ['game_id'], unique=True)
    op.create_table('suspensions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('athlete_id', sa.Integer(), nullable=False),
    sa.Column('championship_id', sa.Integer(), nullable=False),
    sa.Column('games_remaining', sa.Integer(), nullable=False, comment='Jogos que ainda restam cumprir de suspensão'),
    sa.Column('reason', sa.String(length=300), nullable=True, comment='Motivo da suspensão'),
    sa.Column('auto_generated', sa.Boolean(), nullable=False, comment='True quando gerada automaticamente por acúmulo de cartões'),
    sa.ForeignKeyConstraint(['athlete_id'], ['athletes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['championship_id'], ['championships.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_suspensions_athlete_id', 'suspensions', ['athlete_id'], unique=False)
    op.create_index(op.f('ix_suspensions_championship_id'), 'suspensions', ['championship_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_suspensions_championship_id'), table_name='suspensions')
    op.drop_index('ix_suspensions_athlete_id', table_name='suspensions')
    op.drop_table('suspensions')
    op.drop_index(op.f('ix_game_results_game_id'), table_name='game_results')
    op.drop_table('game_results')
    op.drop_index('ix_game_events_type', table_name='game_events')
    op.drop_index('ix_game_events_team_id', table_name='game_events')
    op.drop_index('ix_game_events_game_id', table_name='game_events')
    op.drop_index('ix_game_events_athlete_id', table_name='game_events')
    op.drop_table('game_events')
    op.drop_index('ix_games_status', table_name='games')
    op.drop_index('ix_games_scheduled_at', table_name='games')
    op.drop_index('ix_games_home_team_id', table_name='games')
    op.drop_index('ix_games_championship_id', table_name='games')
    op.drop_index('ix_games_away_team_id', table_name='games')
    op.drop_table('games')
    op.drop_index('uq_championship_team', table_name='championship_teams')
    op.drop_index(op.f('ix_championship_teams_team_id'), table_name='championship_teams')
    op.drop_index(op.f('ix_championship_teams_championship_id'), table_name='championship_teams')
    op.drop_table('championship_teams')
    op.drop_index(op.f('ix_athletes_team_id'), table_name='athletes')
    op.drop_table('athletes')
    op.drop_index(op.f('ix_teams_sport_id'), table_name='teams')
    op.drop_index('ix_teams_created_by', table_name='teams')
    op.drop_table('teams')
    op.drop_index('ix_championships_status', table_name='championships')
    op.drop_index('ix_championships_sport_id', table_name='championships')
    op.drop_index(op.f('ix_championships_created_by'), table_name='championships')
    op.drop_table('championships')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('sports')
    # ### end Alembic commands ###
